"""Regenerate ``vectors/cross_language.json``.

The Kotlin client is validated against known-answer vectors produced by this
script.  Run it after changing the attestation or DNS wire format, then commit
both the vectors and the updated Kotlin expectations.  ``tests/test_vectors.py``
fails if the committed file drifts from what the code actually produces.
"""

from __future__ import annotations

import base64
import json
import pathlib

from ..dns import KNOWN_SINKHOLES, QUERY_ID, encode_query
from ..truth_gate import Attestor

#: Shared by the generated file and the Kotlin unit tests. It is a test key for
#: known-answer vectors only and grants nothing.
TEST_SECRET = b"hyperion-cross-language-test-key"

ATTESTATION_CASES = (
    ("93.184.216.34", 1800000000.0, "nonce-alpha"),
    ("2001:db8::1", 1800000000.123, "nonce-bravo-0123456789"),
    # Deliberately a value whose third decimal is a rounding boundary: if any
    # implementation re-formats the float instead of using the wire string, the
    # signature will not match.
    ("198.51.100.7", 1799999999.9995, "x"),
)

DNS_CASES = (
    ("example.com", 1),
    ("xn--mgba3a4f16a.ir", 1),
    ("a.b.c.d.example.org", 28),
)


def build() -> dict:
    attestor = Attestor(TEST_SECRET)
    attestations = []
    for egress, ts, nonce in ATTESTATION_CASES:
        attestation = attestor.sign(egress, timestamp=ts, nonce=nonce)
        attestations.append(
            {
                "egress_ip": attestation.egress_ip,
                "ts": attestation.timestamp,
                "nonce": attestation.nonce,
                "signature": attestation.signature,
                "canonical": attestation.canonical_payload().decode("ascii"),
                "json": attestor.to_json(attestation).decode("ascii"),
            }
        )

    queries = [
        {
            "name": name,
            "qtype": qtype,
            "query_hex": encode_query(name, qtype).hex(),
            "query_length": len(encode_query(name, qtype)),
        }
        for name, qtype in DNS_CASES
    ]

    return {
        "_comment": (
            "Generated by the Python core. The Kotlin unit tests assert against these "
            "exact values; regenerate with `python3 -m hyperion.tools.gen_vectors`."
        ),
        "generated_by": "python3 -m hyperion.tools.gen_vectors",
        "hmac": {
            "algorithm": "hmac-sha256",
            "secret_b64": base64.b64encode(TEST_SECRET).decode("ascii"),
            "attestations": attestations,
        },
        "dns": {
            "query_id": QUERY_ID,
            "known_sinkholes": sorted(KNOWN_SINKHOLES),
            "queries": queries,
        },
    }


def main() -> int:
    target = pathlib.Path(__file__).resolve().parents[2] / "vectors" / "cross_language.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(build(), indent=2) + "\n")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
